# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = '0b0be8bcc1c72a1d9a6c897578865add'
  config.secret_key = '2e705ddfa8d8ca075fe4c43790e0081c'
  config.default_from = 'thplille@gmail.com'
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  config.api_version = 'v3.1'
end
